./map-server --load-plugin mapcache --map ars_phare
./map-server --load-plugin mapcache --map coppa
./map-server --load-plugin mapcache --map tantale_ile
./map-server --load-plugin mapcache --map ars_phare
./map-server --load-plugin mapcache --map ars_in03
./map-server --load-plugin mapcache --map ars_in04
./map-server --load-plugin mapcache --map ars_in05
./map-server --load-plugin mapcache --map ars_in06
./map-server --load-plugin mapcache --map ars_in07
./map-server --load-plugin mapcache --map ars_in08
./map-server --load-plugin mapcache --map ars_in09
./map-server --load-plugin mapcache --map ars_in10
./map-server --load-plugin mapcache --map ars_in11
./map-server --load-plugin mapcache --map ars_in12
./map-server --load-plugin mapcache --map ars_in13
./map-server --load-plugin mapcache --map ars_in14
./map-server --load-plugin mapcache --map ars_in15
./map-server --load-plugin mapcache --map ars_in16
./map-server --load-plugin mapcache --map ars_in17	
./map-server --load-plugin mapcache --map ars_dun01
./map-server --load-plugin mapcache --map ars_dun02
./map-server --load-plugin mapcache --map ars_dun03
./map-server --load-plugin mapcache --map ars_dun04
./map-server --load-plugin mapcache --map ars_dun05
./map-server --load-plugin mapcache --map ars_dun06
./map-server --load-plugin mapcache --map ars_dun07
./map-server --load-plugin mapcache --map ars_dun08
./map-server --load-plugin mapcache --map ars_dun09
./map-server --load-plugin mapcache --map ars_dun10
./map-server --load-plugin mapcache --map ars_dun11
./map-server --load-plugin mapcache --map ars_dun12
./map-server --load-plugin mapcache --map ars_dun13
./map-server --load-plugin mapcache --map ars_dun14
./map-server --load-plugin mapcache --map ars_dun15
./map-server --load-plugin mapcache --map ars_dun16
./map-server --load-plugin mapcache --map ars_dun17
./map-server --load-plugin mapcache --map ars_dun18
./map-server --load-plugin mapcache --map ars_dun19
./map-server --load-plugin mapcache --map ars_dun20
./map-server --load-plugin mapcache --map ars_dun21
./map-server --load-plugin mapcache --map ars_dun22
./map-server --load-plugin mapcache --map ars_dun23
./map-server --load-plugin mapcache --map ars_dun24
./map-server --load-plugin mapcache --map ars_dun25
./map-server --load-plugin mapcache --map ars_dun26
./map-server --load-plugin mapcache --map ars_dun27
./map-server --load-plugin mapcache --map ars_dun28
./map-server --load-plugin mapcache --map ars_dun29
./map-server --load-plugin mapcache --map ars_dun30
./map-server --load-plugin mapcache --map ars_dun31
./map-server --load-plugin mapcache --map ars_dun32
./map-server --load-plugin mapcache --map ars_dun33
./map-server --load-plugin mapcache --map ars_dun34
./map-server --load-plugin mapcache --map ars_dun35
./map-server --load-plugin mapcache --map ars_dun36
./map-server --load-plugin mapcache --map ars_dun37
./map-server --load-plugin mapcache --map ars_dun38
./map-server --load-plugin mapcache --map ars_dun39
./map-server --load-plugin mapcache --map ars_dun40
./map-server --load-plugin mapcache --map ars_fild01
./map-server --load-plugin mapcache --map ars_fild02
./map-server --load-plugin mapcache --map ars_fild03
./map-server --load-plugin mapcache --map ars_fild04
./map-server --load-plugin mapcache --map ars_fild05
./map-server --load-plugin mapcache --map ars_fild06
./map-server --load-plugin mapcache --map ars_fild07
./map-server --load-plugin mapcache --map ars_fild08
./map-server --load-plugin mapcache --map ars_fild09
./map-server --load-plugin mapcache --map ars_fild10
./map-server --load-plugin mapcache --map ars_fild11
./map-server --load-plugin mapcache --map ars_fild12
./map-server --load-plugin mapcache --map ars_fild13
./map-server --load-plugin mapcache --map ars_fild14
./map-server --load-plugin mapcache --map ars_fild15
./map-server --load-plugin mapcache --map ars_fild16
./map-server --load-plugin mapcache --map ars_fild17
./map-server --load-plugin mapcache --map ars_fild18
./map-server --load-plugin mapcache --map ars_fild19
./map-server --load-plugin mapcache --map ars_fild20
./map-server --load-plugin mapcache --map ars_fild21
./map-server --load-plugin mapcache --map ars_fild22
./map-server --load-plugin mapcache --map ars_fild23
./map-server --load-plugin mapcache --map ars_fild24
./map-server --load-plugin mapcache --map ars_fild25
./map-server --load-plugin mapcache --map ars_fild26
./map-server --load-plugin mapcache --map ars_fild27
./map-server --load-plugin mapcache --map ars_fild28
./map-server --load-plugin mapcache --map ars_fild29
./map-server --load-plugin mapcache --map ars_fild30
./map-server --load-plugin mapcache --map ars_fild31
./map-server --load-plugin mapcache --map ars_fild32
./map-server --load-plugin mapcache --map ars_fild33
./map-server --load-plugin mapcache --map ars_fild34
./map-server --load-plugin mapcache --map ars_fild35
./map-server --load-plugin mapcache --map ars_fild36
./map-server --load-plugin mapcache --map ars_fild37
./map-server --load-plugin mapcache --map ars_fild38
./map-server --load-plugin mapcache --map ars_fild39
./map-server --load-plugin mapcache --map ars_fild40
./map-server --load-plugin mapcache --map ars_fild41
./map-server --load-plugin mapcache --map ars_fild42
./map-server --load-plugin mapcache --map ars_fild43
./map-server --load-plugin mapcache --map ars_fild44
./map-server --load-plugin mapcache --map ars_fild45
./map-server --load-plugin mapcache --map ars_fild46
./map-server --load-plugin mapcache --map ars_fild47
./map-server --load-plugin mapcache --map ars_fild48
./map-server --load-plugin mapcache --map ars_fild49
./map-server --load-plugin mapcache --map ars_fild50
./map-server --load-plugin mapcache --map ars_fild51
./map-server --load-plugin mapcache --map ars_fild52
./map-server --load-plugin mapcache --map ars_fild53
./map-server --load-plugin mapcache --map ars_fild54
./map-server --load-plugin mapcache --map ars_fild55
./map-server --load-plugin mapcache --map ars_fild56
./map-server --load-plugin mapcache --map ars_fild57
./map-server --load-plugin mapcache --map ars_fild58
./map-server --load-plugin mapcache --map ars_fild59
./map-server --load-plugin mapcache --map ars_fild60
./map-server --load-plugin mapcache --map ars_fild61
./map-server --load-plugin mapcache --map ars_fild62