combo_db: (
/*Armaduras ATK*/
{	Items: ["A_Armor_Neutral", "Q_Garmet_Neutral", "Q_Shoes_Neutral"]
	Script: <"	callfunc("Q_combo",Ele_Neutral);	">	},	
{	Items: ["A_Armor_Poison", "Q_Garmet_Poison", "Q_Shoes_Poison"]
	Script: <"	callfunc("Q_combo",Ele_Poison);	">	},	
{	Items: ["A_Armor_Holy", "Q_Garmet_Holy", "Q_Shoes_Holy"]
	Script: <"	callfunc("Q_combo",Ele_Holy);	">	},	
{	Items: ["A_Armor_Dark", "Q_Garmet_Dark", "Q_Shoes_Dark"]
	Script: <"	callfunc("Q_combo",Ele_Dark);	">	},	
{	Items: ["A_Armor_Fire", "Q_Garmet_Fire", "Q_Shoes_Fire"]
	Script: <"	callfunc("Q_combo",Ele_Fire);	">	},
{	Items: ["A_Armor_Water", "Q_Garmet_Water", "Q_Shoes_Water"]
	Script: <"	callfunc("Q_combo",Ele_Water);	">	},	
{	Items: ["A_Armor_Wind", "Q_Garmet_Wind", "Q_Shoes_Wind"]
	Script: <"	callfunc("Q_combo",Ele_Wind);	">	},	
{	Items: ["A_Armor_Earth", "Q_Garmet_Earth", "Q_Shoes_Earth"]
	Script: <"	callfunc("Q_combo",Ele_Earth);	">	},	
{	Items: ["A_Armor_Undead", "Q_Garmet_Undead", "Q_Shoes_Undead"]
	Script: <"	callfunc("Q_combo",Ele_Undead);	">	},	
{	Items: ["A_Armor_Ghost", "Q_Garmet_Ghost", "Q_Shoes_Ghost"]
	Script: <"	callfunc("Q_combo",Ele_Ghost);	">	},
/*Armaduras MATK*/
{	Items: ["M_Armor_Neutral", "Q_Garmet_Neutral", "Q_Shoes_Neutral"]
	Script: <"	callfunc("Q_combo",Ele_Neutral);	">	},	
{	Items: ["M_Armor_Poison", "Q_Garmet_Poison", "Q_Shoes_Poison"]
	Script: <"	callfunc("Q_combo",Ele_Poison);	">	},	
{	Items: ["M_Armor_Holy", "Q_Garmet_Holy", "Q_Shoes_Holy"]
	Script: <"	callfunc("Q_combo",Ele_Holy);	">	},	
{	Items: ["M_Armor_Dark", "Q_Garmet_Dark", "Q_Shoes_Dark"]
	Script: <"	callfunc("Q_combo",Ele_Dark);	">	},	
{	Items: ["M_Armor_Fire", "Q_Garmet_Fire", "Q_Shoes_Fire"]
	Script: <"	callfunc("Q_combo",Ele_Fire);	">	},
{	Items: ["M_Armor_Water", "Q_Garmet_Water", "Q_Shoes_Water"]
	Script: <"	callfunc("Q_combo",Ele_Water);	">	},	
{	Items: ["M_Armor_Wind", "Q_Garmet_Wind", "Q_Shoes_Wind"]
	Script: <"	callfunc("Q_combo",Ele_Wind);	">	},	
{	Items: ["M_Armor_Earth", "Q_Garmet_Earth", "Q_Shoes_Earth"]
	Script: <"	callfunc("Q_combo",Ele_Earth);	">	},	
{	Items: ["M_Armor_Undead", "Q_Garmet_Undead", "Q_Shoes_Undead"]
	Script: <"	callfunc("Q_combo",Ele_Undead);	">	},	
{	Items: ["M_Armor_Ghost", "Q_Garmet_Ghost", "Q_Shoes_Ghost"]
	Script: <"	callfunc("Q_combo",Ele_Ghost);	">	},
/*Armaduras Duales*/
{	Items: ["D_Armor_Neutral", "Q_Garmet_Neutral", "Q_Shoes_Neutral"]
	Script: <"	callfunc("Q_combo",Ele_Neutral);	">	},	
{	Items: ["D_Armor_Poison", "Q_Garmet_Poison", "Q_Shoes_Poison"]
	Script: <"	callfunc("Q_combo",Ele_Poison);	">	},	
{	Items: ["D_Armor_Holy", "Q_Garmet_Holy", "Q_Shoes_Holy"]
	Script: <"	callfunc("Q_combo",Ele_Holy);	">	},	
{	Items: ["D_Armor_Dark", "Q_Garmet_Dark", "Q_Shoes_Dark"]
	Script: <"	callfunc("Q_combo",Ele_Dark);	">	},	
{	Items: ["D_Armor_Fire", "Q_Garmet_Fire", "Q_Shoes_Fire"]
	Script: <"	callfunc("Q_combo",Ele_Fire);	">	},
{	Items: ["D_Armor_Water", "Q_Garmet_Water", "Q_Shoes_Water"]
	Script: <"	callfunc("Q_combo",Ele_Water);	">	},	
{	Items: ["D_Armor_Wind", "Q_Garmet_Wind", "Q_Shoes_Wind"]
	Script: <"	callfunc("Q_combo",Ele_Wind);	">	},	
{	Items: ["D_Armor_Earth", "Q_Garmet_Earth", "Q_Shoes_Earth"]
	Script: <"	callfunc("Q_combo",Ele_Earth);	">	},	
{	Items: ["D_Armor_Undead", "Q_Garmet_Undead", "Q_Shoes_Undead"]
	Script: <"	callfunc("Q_combo",Ele_Undead);	">	},	
{	Items: ["D_Armor_Ghost", "Q_Garmet_Ghost", "Q_Shoes_Ghost"]
	Script: <"	callfunc("Q_combo",Ele_Ghost);	">	},
)