/*========================================================*/
/*Commandos Script*/
"aragor/npc/functions/atcommand/refineUI.src",
"aragor/npc/functions/atcommand/mail.txt",
/*Commandos Script*/
/*========================================================*/
"aragor/npc/functions/card/Elemental_card.src",
/*Mvp card count*/
"aragor/npc/functions/card/MVP_Card.src",
"aragor/npc/functions/card/F_contar_cartas.src",
/*Mvp card count*/
/*========================================================*/
/*Healer*/
"aragor/npc/functions/heal/F_HealBuff.txt",
/*========================================================*/
/*Weapons*/
"aragor/npc/functions/weapon/Q_Daggers.src",/*1*/
"aragor/npc/functions/weapon/Q_1HSword.src",/*2*/
"aragor/npc/functions/weapon/Q_2HSword.src",/*2*/
"aragor/npc/functions/weapon/Q_Spear.src",/*3*/
"aragor/npc/functions/weapon/Q_Axes.src",/*4*/
"aragor/npc/functions/weapon/Q_MacesHP.src",/*5*/
"aragor/npc/functions/weapon/Q_Taekwon.src",/*5*/
"aragor/npc/functions/weapon/Q_Staff.src",/*6*/
"aragor/npc/functions/weapon/Q_Bows.src",/*7*/
"aragor/npc/functions/weapon/Q_Knuckles.src",/*8*/
"aragor/npc/functions/weapon/Q_Guitars.src",/*9*/
"aragor/npc/functions/weapon/Q_Whips.src",/*10*/
"aragor/npc/functions/weapon/Q_Books.src",/*11*/
"aragor/npc/functions/weapon/Q_Katar.src",/*12*/
"aragor/npc/functions/weapon/Q_Shurikens.src",/*13*/
"aragor/npc/functions/weapon/Q_Guns.src",/*14*/
/*Ammo*/
"aragor/npc/functions/weapon/Q_Ammo.src",
/*===================================================*/
"aragor/npc/functions/tools/F_GuaranteeRefine2.src",
/*==================QUEST============================*/
"aragor/npc/functions/Quest/Q_Armor_M.src",
"aragor/npc/functions/Quest/Q_Armor_A.src",
"aragor/npc/functions/Quest/Q_Garmet.src",
"aragor/npc/functions/Quest/Q_Shoes.src",
"aragor/npc/functions/Quest/Q_Shield.src",
"aragor/npc/functions/Quest/Q_Hat.src",
"aragor/npc/functions/Quest/Q_Mid.src",
"aragor/npc/functions/Quest/Q_Wings.src",
"aragor/npc/functions/Quest/Q_Accessory.src",
/*==================Novice===========================*/
"aragor/npc/functions/Novice/Q_Garmet.src",
"aragor/npc/functions/Novice/Q_Shield.src",
"aragor/npc/functions/Novice/Q_Weapons.src",
"aragor/npc/functions/Novice/Q_Shoes.src",
/*=================PREMIUM===========================*/
"aragor/npc/functions/Premium/P_Armor.src",
"aragor/npc/functions/Premium/P_Garmet.src",
"aragor/npc/functions/Premium/P_Shoes.src",
"aragor/npc/functions/Premium/P_Wing.src",
"aragor/npc/functions/Premium/P_Hat.src",
"aragor/npc/functions/Premium/P_Accessory.src",
"aragor/npc/functions/Premium/P_SuperMid.src",