/*========================================================*/
/*Commandos Script*/
"aragor/npc/functions/atcommand/refineUI.src",
"aragor/npc/functions/atcommand/mail.txt",
/*Commandos Script*/
/*========================================================*/
"aragor/npc/functions/card/Elemental_card.src",
/*Mvp card count*/
"aragor/npc/functions/card/MVP_Card.src",
"aragor/npc/functions/card/F_contar_cartas.src",
/*Mvp card count*/
/*========================================================*/
/*Healer*/
"aragor/npc/functions/heal/F_HealBuff.txt",
/*========================================================*/
/*Weapons*/
"aragor/npc/functions/weapon/Q_DAGGER.src",/*1*/
"aragor/npc/functions/weapon/Q_1HSWORD.src",/*2*/
"aragor/npc/functions/weapon/Q_2HSWORD.src",/*2*/
"aragor/npc/functions/weapon/Q_SPEAR.src",/*3*/
"aragor/npc/functions/weapon/Q_AXE.src",/*4*/
"aragor/npc/functions/weapon/Q_MACE_HP.src",/*5*/
"aragor/npc/functions/weapon/Q_TAEKWON.src",/*5*/
"aragor/npc/functions/weapon/Q_STAFF.src",/*6*/
"aragor/npc/functions/weapon/Q_BOW.src",/*7*/
"aragor/npc/functions/weapon/Q_KNUCKLE.src",/*8*/
"aragor/npc/functions/weapon/Q_MUSICAL.src",/*9*/
"aragor/npc/functions/weapon/Q_WHIP.src",/*10*/
"aragor/npc/functions/weapon/Q_BOOK.src",/*11*/
"aragor/npc/functions/weapon/Q_KATAR.src",/*12*/
"aragor/npc/functions/weapon/P_KATAR.src",/*12*/
"aragor/npc/functions/weapon/Q_HUUMA.src",/*13*/
"aragor/npc/functions/weapon/Q_GUNS.src",/*14*/
/*===================================================*/
"aragor/npc/functions/tools/F_GuaranteeRefine2.src",
/*==================QUEST============================*/
"aragor/npc/functions/Quest/Q_Armor_M.src",
"aragor/npc/functions/Quest/Q_Armor_A.src",
"aragor/npc/functions/Quest/Q_Garmet.src",
"aragor/npc/functions/Quest/Q_Shoes.src",
"aragor/npc/functions/Quest/Q_Shield.src",
"aragor/npc/functions/Quest/Q_Hat.src",
"aragor/npc/functions/Quest/Q_Mid.src",
"aragor/npc/functions/Quest/Q_Wings.src",
"aragor/npc/functions/Quest/Q_Accessory.src",
/*==================Novice===========================*/
"aragor/npc/functions/Novice/Q_Garmet.src",
"aragor/npc/functions/Novice/Q_Shield.src",
"aragor/npc/functions/Novice/Q_Weapons.src",
"aragor/npc/functions/Novice/Q_Shoes.src",
/*=================PREMIUM===========================*/
"aragor/npc/functions/Premium/P_Armor.src",
"aragor/npc/functions/Premium/P_Garmet.src",
"aragor/npc/functions/Premium/P_Shoes.src",
"aragor/npc/functions/Premium/P_Wing.src",
"aragor/npc/functions/Premium/P_Hat.src",
"aragor/npc/functions/Premium/P_Accessory.src",
"aragor/npc/functions/Premium/P_SuperMid.src",