//================= Basic Scripts ======================================
"aragor/npc/tools/healer.txt",
"aragor/npc/tools/warper.txt",
"aragor/npc/tools/stylist.txt",
"aragor/npc/tools/SuperMid.src",
"aragor/npc/tools/novice_valis.txt",
"aragor/npc/tools/Anti-Bot.txt",
"aragor/npc/tools/breeder.src",
"aragor/npc/tools/platinum_skills.src",
//================= Zona ViP =========================================
"aragor/npc/zona_quest/vip_shop.txt",
//================= Zona Quest =======================================
"aragor/npc/zona_quest/zona_quest.src",
"aragor/npc/zona_quest/weapon_shop.src",
"aragor/npc/zona_quest/armor_shop.src",
"aragor/npc/zona_quest/armeria_vip.txt",
//================= Eventos ==========================================
//"aragor/npc/eventos/aEvent.src",
//"aragor/npc/eventos/aPortal.src",/* aPortal */
//"aragor/npc/eventos/casillas.src",/* Evento Casillas */
//"aragor/npc/eventos/laberinto.src",/* Evento Laberinto */
//"aragor/npc/eventos/novicevszombie.src",/* Evento Novice vs Zombie */
//"aragor/npc/eventos/poringfake.src",/* Evento Porings */
//"aragor/npc/eventos/empbreak.src",/* Evento Emperium Break */
//"aragor/npc/eventos/poringrace.src",/* Evento Porings Race */
//"aragor/npc/eventos/aquademons.src",/* Evento Demonios Del Agua */
//"aragor/npc/eventos/satan_invacion.src",/* Evento Invacion Satan */
//"aragor/npc/eventos/run_or_die.src",/* Evento Run or die */
//========================== Maps ===================================
"aragor/npc/warps/dungeons/arsione.src",
//========================== Mobs ===================================

//========================== TEST ===================================
"aragor/npc/optionmaster.src",