//================= Hercules Configuration ================================
//=       _   _                     _
//=      | | | |                   | |
//=      | |_| | ___ _ __ ___ _   _| | ___  ___
//=      |  _  |/ _ \ '__/ __| | | | |/ _ \/ __|
//=      | | | |  __/ | | (__| |_| | |  __/\__ \
//=      \_| |_/\___|_|  \___|\__,_|_|\___||___/
//================= License ===============================================
//= This file is part of Hercules.
//= http://herc.ws - http://github.com/HerculesWS/Hercules
//=
//= Copyright (C) 2014-2020 Hercules Dev Team
//=
//= Hercules is free software: you can redistribute it and/or modify
//= it under the terms of the GNU General Public License as published by
//= the Free Software Foundation, either version 3 of the License, or
//= (at your option) any later version.
//=
//= This program is distributed in the hope that it will be useful,
//= but WITHOUT ANY WARRANTY; without even the implied warranty of
//= MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//= GNU General Public License for more details.
//=
//= You should have received a copy of the GNU General Public License
//= along with this program.  If not, see <http://www.gnu.org/licenses/>.
//=========================================================================
//= Battle local configuration file.
//=========================================================================

battle_configuration: {
	// ExtendedBG
	@include "conf/import/battle/eBG.conf"

	// General battle-related settings.
	@include "conf/import/battle/battle.conf"

	// Settings specific to the client.
	@include "conf/import/battle/client.conf"

	// General drop-related configs.
	@include "conf/import/battle/drops.conf"

	// Experience rates, exp penalties, stats and max level settings.
	@include "conf/import/battle/exp.conf"

	// GM levels, atcommands and hack-related configs.
	@include "conf/import/battle/gm.conf"

	// Guild and WoE settings
	@include "conf/import/battle/guild.conf"

	// Battleground settings
	@include "conf/import/battle/battleground.conf"

	// Item/card-specific and crafting related options.
	@include "conf/import/battle/items.conf"

	// Mob related configuration
	@include "conf/import/battle/monster.conf"

	// Party related configuration
	@include "conf/import/battle/party.conf"

	// Pet related configuration
	@include "conf/import/battle/pet.conf"

	// Homunc related configuration
	@include "conf/import/battle/homunc.conf"

	// Player specific settings
	@include "conf/import/battle/player.conf"

	// Skill related settings
	@include "conf/import/battle/skill.conf"

	// Status change related settings
	@include "conf/import/battle/status.conf"

	// Feature control (on/off) settings
	@include "conf/import/battle/feature.conf"

	// Anything else that didn't fit anywhere else.
	// Includes duel, day/night, mute/manner, log settings.
	@include "conf/import/battle/misc.conf"
}